// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShowTheShortcut
{
    static class Vsix
    {
        public const string Id = "9da28329-f9d5-4f18-91c3-d3285b103d1a";
        public const string Name = "Show The Shortcut";
        public const string Description = "Shows the keyboard shortcut for any command that you execute to help you learn the shortcuts you use the most.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "keyboard, shortcut, commands";
    }
}
